// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIn3xTgnFXhQlYfOu6p0brg0gApc7SMWU',
    appId: '1:41362966106:web:6ba3d0a6e02b79a5d8fa63',
    messagingSenderId: '41362966106',
    projectId: 'kwye-57e40',
    authDomain: 'kwye-57e40.firebaseapp.com',
    storageBucket: 'kwye-57e40.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByHId1tojVJGUWdPQrkMqTW9xIC1xiw1I',
    appId: '1:41362966106:ios:a730f646226126a5d8fa63',
    messagingSenderId: '41362966106',
    projectId: 'kwye-57e40',
    storageBucket: 'kwye-57e40.appspot.com',
    iosBundleId: 'com.example.kwye',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIn3xTgnFXhQlYfOu6p0brg0gApc7SMWU',
    appId: '1:41362966106:web:5955929418c949eed8fa63',
    messagingSenderId: '41362966106',
    projectId: 'kwye-57e40',
    authDomain: 'kwye-57e40.firebaseapp.com',
    storageBucket: 'kwye-57e40.appspot.com',
  );
}
